(* ::Package:: *)

intSubSqt[f_,x_]:=Module[
	{pos,e=f,r,a,b,c,A,C,y,z,trans},
	pos=Position[e,Power[y_,1/2]];
	r=Extract[e,pos];
	a=r[[1,1,1]];
	b=r[[1,1,2,1]];
	c=r[[1,1,3,1]];
	(*If[D[a,x]!=0||D[b,x]!=0||D[c,x]!=0,Return["NotMatch"]];*)
	a=b-4a*c;
	b=a;
	c=b-4a*c;
	a=r[[1,1,1]];
	b=r[[1,1,2,1]];
	c=r[[1,1,3,1]];
	A=a-b^2/(4c);
	C=c;
	e=e/.x->(y-b/(2c));
	If[C>0;A>0,
		e=e/.y->(Tan[z]/Sqrt[C/A]);
		pos=Position[e,Power[y_,1/2]];
		r=Extract[e,pos][[1]];
		e=e/.r->Tan[z];
		trans=ArcTan[Sqrt[C/A]*(x+b/(2c))]
	];
	If[C>0;A<0,
		e=e/.y->(Sec[z]/Sqrt[C/-A]);
		pos=Position[e,Power[y_,1/2]];
		r=Extract[e,pos][[1]];
		e=e/.r->Sec[z];
		trans=ArcSin[Sqrt[-C/A]*(x+b/(2c))]
	];
	If[C>0;A=0,
		e=e/.y->(z/Sqrt[C]);
		pos=Position[e,Power[y_,1/2]];
		r=Extract[e,pos][[1]];
		e=e/.r->z;
		trans=Sqrt[C]*(x+b/(2c))
	];
	If[C<0;A>0,
		e=e/.y->(Sin[z]*Sqrt[-C/A])
		pos=Position[e,Power[y_,1/2]];
		r=Extract[e,pos][[1]];
		e=e/.r->Cos[z];
		trans=ArcSec[Sqrt[-C/A]*(x+b/(2c))]
	];
	
	Return[{Simplify[e],z,trans}]
]

